### ISSUE TITLE
Demo project does not compile

### ISSUE THREAD

**Issue by colasjojo** [Mazyod/MJAutoComplete#4]
If I open the demo project and try to execute it, I have the following error:

![capture d ecran 2015-04-08 a 12 56 18](https://cloud.githubusercontent.com/assets/4303814/7043949/c26493e2-ddee-11e4-832b-35cd382b096d.png)

**Comment by Mazyod** [comment]
Hi!

Please update the submodules. 
To do that, open terminal, cd into the repo root and execute:

```bash
$ git submodule update --init --recursive
```

**Comment by Mazyod** [comment]
I added a note about that in the readme. Thanks again for bringing this up

**Comment by colasjojo** [comment]
Are you sure? Because, I have tried also to download manually `AFNNet...` and it seemed that the files of the current version were different from the requested files. (maybe my mistake or my misunderstanding).

Anyway, for the sake of simplicity for newbies, I would advise you to directly copy the files of `AFN...` in your project.

Your solution is clearly more elegant and save more space... but imagine someone in a hurry who wants to have a quick look of the different libraries for autocompletion (and who is not maybe very at ease with `git`... I don't what is a submodule, neither a module, for instance)...

Thanks anyway

**Comment by Mazyod** [comment]
@colasjojo I agree that it should be simpler, and I opened another issue for hits (see #5). The problem you're seeing is because SDWebImage itself has submodules, and hence you need the `recursive` flag. I am 90% sure that's the issue, but I could always be wrong.
