### ISSUE TITLE
Simplify example project

### ISSUE THREAD

**Issue by Mazyod** [Mazyod/MJAutoComplete#5]

**Comment by Mazyod** [comment]
Thanks to @colasjojo input, its probably an overkill to have SDWebImage for this project, which needs recursive submodule update.

We should migrate to Hanake for simplicity sake.

**Comment by colasjojo** [comment]
+1

**Comment by colasjojo** [comment]
Thanks, it works.

**Comment by Mazyod** [comment]
:+1:
